-- Your own general overrides.
--
-- Sourced after the shipped config, so anything set here wins. This file is
-- written once when Mainstream is installed and never touched again, which is
-- what makes it safe to edit.
--
-- Plugin loading and plugin settings used to live here and have moved to
-- hyprland/plugins.lua, because they are the project's own machinery rather
-- than anybody's overrides, and kept here they only ever reached new installs.
--
-- Example:
--   hl.config({ general = { gaps_in = 6 } })
