#!/usr/bin/env bash
set -u

folder_color="${PAPIRUS_FOLDER_COLOR:-}"
source_hex="${PAPIRUS_SOURCE_HEX:-}"
theme_name="${PAPIRUS_MATUGEN_THEME:-Papirus-Matugen}"
theme_dir="${XDG_DATA_HOME:-$HOME/.local/share}/icons/$theme_name"
state_dir="${XDG_STATE_HOME:-$HOME/.local/state}/matugen"
state_file="$state_dir/papirus-folder-color"

mkdir -p "$state_dir"

[ -n "$source_hex" ] || source_hex="{{ colors.source_color.default.hex }}"
[ -n "$source_hex" ] || source_hex="{{ colors.primary.default.hex }}"

source_hex="${source_hex#\#}"
case "$source_hex" in
  ??????) ;;
  *)
    source_hex="5294e2"
    ;;
esac

if [ -z "$folder_color" ]; then
  if command -v python3 >/dev/null 2>&1; then
    folder_color="$(python3 - "$source_hex" <<'PY'
import colorsys
import sys

source = sys.argv[1]
palette = {
    "adwaita": "#3a87e5",
    "black": "#3f3f3f",
    "blue": "#4877b1",
    "bluegrey": "#4d646f",
    "breeze": "#147eb8",
    "brown": "#957552",
    "carmine": "#7a0002",
    "cyan": "#0096aa",
    "darkcyan": "#35818a",
    "deeporange": "#e95420",
    "green": "#60924b",
    "grey": "#727272",
    "indigo": "#3f51b5",
    "magenta": "#b259b8",
    "nordic": "#5e81ac",
    "orange": "#dd772f",
    "palebrown": "#bea389",
    "paleorange": "#c89e6b",
    "pink": "#ec407a",
    "red": "#bf4b4b",
    "teal": "#12806a",
    "violet": "#5d399b",
    "white": "#cccccc",
    "yaru": "#973552",
    "yellow": "#e19d00",
}

def rgb(hex_value):
    hex_value = hex_value.lstrip("#")
    return tuple(int(hex_value[index:index + 2], 16) / 255 for index in (0, 2, 4))

source_hsv = colorsys.rgb_to_hsv(*rgb(source))
if source_hsv[1] < 0.08:
    print("white" if source_hsv[2] > 0.70 else "grey" if source_hsv[2] > 0.35 else "black")
    raise SystemExit

def score(hex_value):
    hsv = colorsys.rgb_to_hsv(*rgb(hex_value))
    hue_distance = min(abs(source_hsv[0] - hsv[0]), 1 - abs(source_hsv[0] - hsv[0]))
    saturation_distance = abs(source_hsv[1] - hsv[1])
    value_distance = abs(source_hsv[2] - hsv[2])
    return hue_distance * 5 + saturation_distance * 0.75 + value_distance * 0.2

print(min(palette, key=lambda name: score(palette[name])))
PY
)"
  fi

  if [ -z "$folder_color" ]; then
    r=$((16#${source_hex:0:2}))
    g=$((16#${source_hex:2:2}))
    b=$((16#${source_hex:4:2}))
    best="blue"
    bestd=99999999

    while read -r name pr pg pb; do
      d=$(( (r - pr) * (r - pr) + (g - pg) * (g - pg) + (b - pb) * (b - pb) ))
      if [ "$d" -lt "$bestd" ]; then
        bestd="$d"
        best="$name"
      fi
    done <<'COLORS'
red 191 75 75
yellow 225 157 0
green 96 146 75
teal 18 128 106
cyan 0 150 170
blue 72 119 177
indigo 63 81 181
violet 93 57 155
magenta 178 89 184
pink 236 64 122
orange 221 119 47
deeporange 233 84 32
brown 149 117 82
grey 114 114 114
bluegrey 77 100 111
carmine 122 0 2
black 63 63 63
COLORS

    folder_color="$best"
  fi
fi

case "$folder_color" in
  adwaita|black|blue|bluegrey|breeze|brown|carmine|cyan|darkcyan|deeporange|green|grey|indigo|magenta|nordic|orange|palebrown|paleorange|pink|red|teal|violet|white|yaru|yellow) ;;
  *)
    folder_color="blue"
    ;;
esac

current_theme=""
if command -v gsettings >/dev/null 2>&1; then
  current_theme="$(gsettings get org.gnome.desktop.interface icon-theme 2>/dev/null | tr -d "'")"
fi

base_theme="${PAPIRUS_MATUGEN_BASE_THEME:-}"
if [ -z "$base_theme" ]; then
  case "$current_theme" in
    Papirus-Matugen|Papirus-Dark|Papirus-Dark-Matugen) base_theme="Papirus-Dark" ;;
    Papirus-Light|Papirus-Light-Matugen) base_theme="Papirus-Light" ;;
    Papirus|Papirus-Matugen-Light) base_theme="Papirus" ;;
    *) base_theme="Papirus-Dark" ;;
  esac
fi

if [ ! -d "/usr/share/icons/$base_theme" ]; then
  base_theme="Papirus-Dark"
fi

mkdir -p "$theme_dir"
printf '%s\n' "$folder_color" > "$state_file"
printf '#%s\n' "$source_hex" > "$state_file.hex"

cat > "$theme_dir/index.theme" <<EOF
[Icon Theme]
Name=$theme_name
Comment=Papirus folder color overlay generated by matugen
Inherits=$base_theme,hicolor
Example=folder
FollowsColorScheme=true
Directories=16x16/places,22x22/places,24x24/places,32x32/places,48x48/places,64x64/places

[16x16/places]
Context=Places
Size=16
Type=Fixed

[22x22/places]
Context=Places
Size=22
Type=Fixed

[24x24/places]
Context=Places
Size=24
Type=Fixed

[32x32/places]
Context=Places
Size=32
Type=Fixed

[48x48/places]
Context=Places
Size=48
Type=Fixed

[64x64/places]
Context=Places
Size=64
Type=Fixed
EOF

for size in 16x16 22x22 24x24 32x32 48x48 64x64; do
  target_dir="$theme_dir/$size/places"
  source_dir="/usr/share/icons/$base_theme/$size/places"
  [ -d "$source_dir" ] || source_dir="/usr/share/icons/Papirus/$size/places"
  [ -d "$source_dir" ] || continue

  rm -rf "$target_dir"
  mkdir -p "$target_dir"

  for icon in "$source_dir"/folder-"$folder_color"*.svg; do
    [ -e "$icon" ] || continue
    name="$(basename "$icon")"
    case "$name" in
      folder-"$folder_color".svg) alias="folder.svg" ;;
      folder-"$folder_color"-*) alias="folder-${name#folder-$folder_color-}" ;;
      *) continue ;;
    esac
    ln -s "$icon" "$target_dir/$alias"
  done
done

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -q -f -t "$theme_dir" >/dev/null 2>&1 || true
fi

if command -v gsettings >/dev/null 2>&1; then
  gsettings set org.gnome.desktop.interface icon-theme "$base_theme" >/dev/null 2>&1 || true
  gsettings set org.gnome.desktop.interface icon-theme "$theme_name" >/dev/null 2>&1 || true
fi

if command -v kwriteconfig6 >/dev/null 2>&1; then
  kwriteconfig6 --file kdeglobals --group Icons --key Theme "$theme_name" >/dev/null 2>&1 || true
elif command -v kwriteconfig5 >/dev/null 2>&1; then
  kwriteconfig5 --file kdeglobals --group Icons --key Theme "$theme_name" >/dev/null 2>&1 || true
fi

if command -v qdbus6 >/dev/null 2>&1; then
  qdbus6 org.kde.KGlobalSettings /KGlobalSettings notifyChange 4 0 >/dev/null 2>&1 || true
elif command -v qdbus >/dev/null 2>&1; then
  qdbus org.kde.KGlobalSettings /KGlobalSettings notifyChange 4 0 >/dev/null 2>&1 || true
fi
